testing:
    database:
        dbName: 'bookstore_test'
        dbUser: 'root'
        dbPassword: 'omelette'
development:
    server:
        port: '3000'
        host: 'http://localhost'
    database:
        dbName: 'bookstore'
        dbUser: 'root'
        dbPassword: 'omelette'
production:
    server:
        port:
        host:
    database:
        dbName:
        dbUser:
        dbPassword:
